apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
  namespace: production
spec:
  containers:
    - name: app
      image: nginx:alpine
      volumeMounts:
        - mountPath: /host
          name: host-vol
  volumes:
    - name: host-vol
      hostPath:
        path: /     # VIOLATION: mounts entire host filesystem